//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeClinic.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyeClinic.WPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Diagnosis.
        /// </summary>
        internal static string AddDiagnosis {
            get {
                return ResourceManager.GetString("AddDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add For Near Vision.
        /// </summary>
        internal static string AddForNearVision {
            get {
                return ResourceManager.GetString("AddForNearVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Of Injury.
        /// </summary>
        internal static string AgeOfInjury {
            get {
                return ResourceManager.GetString("AgeOfInjury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Setting.
        /// </summary>
        internal static string AppSetting {
            get {
                return ResourceManager.GetString("AppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wanna exit ?.
        /// </summary>
        internal static string AreYouSureExit {
            get {
                return ResourceManager.GetString("AreYouSureExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar Name.
        /// </summary>
        internal static string ArName {
            get {
                return ResourceManager.GetString("ArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Medicines.
        /// </summary>
        internal static string AvailableMedicines {
            get {
                return ResourceManager.GetString("AvailableMedicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Usage.
        /// </summary>
        internal static string AvailableUsage {
            get {
                return ResourceManager.GetString("AvailableUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Cost.
        /// </summary>
        internal static string ClinicCost {
            get {
                return ResourceManager.GetString("ClinicCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt.
        /// </summary>
        internal static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        internal static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseases List.
        /// </summary>
        internal static string DiseasesList {
            get {
                return ResourceManager.GetString("DiseasesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done :.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped.
        /// </summary>
        internal static string Dropped {
            get {
                return ResourceManager.GetString("Dropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Name.
        /// </summary>
        internal static string EnName {
            get {
                return ResourceManager.GetString("EnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Password.
        /// </summary>
        internal static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Test.
        /// </summary>
        internal static string EyeTest {
            get {
                return ResourceManager.GetString("EyeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Test Code.
        /// </summary>
        internal static string EyeTestCode {
            get {
                return ResourceManager.GetString("EyeTestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        internal static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By :.
        /// </summary>
        internal static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Visit.
        /// </summary>
        internal static string FinishVisit {
            get {
                return ResourceManager.GetString("FinishVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        internal static string Glass {
            get {
                return ResourceManager.GetString("Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        internal static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        internal static string IsDrawing {
            get {
                return ResourceManager.GetString("IsDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinking.
        /// </summary>
        internal static string IsDrinking {
            get {
                return ResourceManager.GetString("IsDrinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking.
        /// </summary>
        internal static string IsSmoking {
            get {
                return ResourceManager.GetString("IsSmoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Tests.
        /// </summary>
        internal static string LabTests {
            get {
                return ResourceManager.GetString("LabTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Measure.
        /// </summary>
        internal static string LastMeasure {
            get {
                return ResourceManager.GetString("LastMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Eye.
        /// </summary>
        internal static string LeftEye {
            get {
                return ResourceManager.GetString("LeftEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Eye Operation.
        /// </summary>
        internal static string LeftEyeOperation {
            get {
                return ResourceManager.GetString("LeftEyeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Eye Result.
        /// </summary>
        internal static string LeftEyeResult {
            get {
                return ResourceManager.GetString("LeftEyeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Status.
        /// </summary>
        internal static string MartialStatus {
            get {
                return ResourceManager.GetString("MartialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Measure.
        /// </summary>
        internal static string MaxMeasure {
            get {
                return ResourceManager.GetString("MaxMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Center :.
        /// </summary>
        internal static string MedicalCenter {
            get {
                return ResourceManager.GetString("MedicalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Code.
        /// </summary>
        internal static string MedicineCode {
            get {
                return ResourceManager.GetString("MedicineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Name.
        /// </summary>
        internal static string MedicineName {
            get {
                return ResourceManager.GetString("MedicineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Type.
        /// </summary>
        internal static string MedicineType {
            get {
                return ResourceManager.GetString("MedicineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Name.
        /// </summary>
        internal static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Glass.
        /// </summary>
        internal static string NewGlass {
            get {
                return ResourceManager.GetString("NewGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO DATA.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Paid.
        /// </summary>
        internal static string NotPaid {
            get {
                return ResourceManager.GetString("NotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Schedule.
        /// </summary>
        internal static string OperationsSchedule {
            get {
                return ResourceManager.GetString("OperationsSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Word  :.
        /// </summary>
        internal static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Code.
        /// </summary>
        internal static string PatientCode {
            get {
                return ResourceManager.GetString("PatientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient File.
        /// </summary>
        internal static string PatientFile {
            get {
                return ResourceManager.GetString("PatientFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Info.
        /// </summary>
        internal static string PatientInfo {
            get {
                return ResourceManager.GetString("PatientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients list.
        /// </summary>
        internal static string PatientList {
            get {
                return ResourceManager.GetString("PatientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        internal static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Service Group.
        /// </summary>
        internal static string PatientServiceGroup {
            get {
                return ResourceManager.GetString("PatientServiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set this payment as Paid, it must be equal or less than today date.
        /// </summary>
        internal static string PaymentDateShouldBeEqualOrLessToday {
            get {
                return ResourceManager.GetString("PaymentDateShouldBeEqualOrLessToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Location :.
        /// </summary>
        internal static string PaymentLocation {
            get {
                return ResourceManager.GetString("PaymentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments Type.
        /// </summary>
        internal static string PaymentsType {
            get {
                return ResourceManager.GetString("PaymentsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending  :.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone :.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Source :.
        /// </summary>
        internal static string PhotoSource {
            get {
                return ResourceManager.GetString("PhotoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Details.
        /// </summary>
        internal static string PrescriptionDetails {
            get {
                return ResourceManager.GetString("PrescriptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescriptions.
        /// </summary>
        internal static string Prescriptions {
            get {
                return ResourceManager.GetString("Prescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Glass.
        /// </summary>
        internal static string PreviousGlass {
            get {
                return ResourceManager.GetString("PreviousGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Test Page.
        /// </summary>
        internal static string PrintTestPage {
            get {
                return ResourceManager.GetString("PrintTestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready Prescriptions.
        /// </summary>
        internal static string ReadyPrescriptions {
            get {
                return ResourceManager.GetString("ReadyPrescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining :.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me.
        /// </summary>
        internal static string RemindMe {
            get {
                return ResourceManager.GetString("RemindMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request New Tests.
        /// </summary>
        internal static string RequestNewTests {
            get {
                return ResourceManager.GetString("RequestNewTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Eye :.
        /// </summary>
        internal static string RightEye {
            get {
                return ResourceManager.GetString("RightEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Eye Operation.
        /// </summary>
        internal static string RightEyeOperation {
            get {
                return ResourceManager.GetString("RightEyeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Eye Result.
        /// </summary>
        internal static string RightEyeResult {
            get {
                return ResourceManager.GetString("RightEyeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Print.
        /// </summary>
        internal static string SaveAndPrint {
            get {
                return ResourceManager.GetString("SaveAndPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions :.
        /// </summary>
        internal static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Lab Test Result.
        /// </summary>
        internal static string SetLabTestResult {
            get {
                return ResourceManager.GetString("SetLabTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Completed.
        /// </summary>
        internal static string ShowCompleted {
            get {
                return ResourceManager.GetString("ShowCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick Story.
        /// </summary>
        internal static string SickStory {
            get {
                return ResourceManager.GetString("SickStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Cash Amount.
        /// </summary>
        internal static string StartCashAmount {
            get {
                return ResourceManager.GetString("StartCashAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started :.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Service.
        /// </summary>
        internal static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Code.
        /// </summary>
        internal static string TestCode {
            get {
                return ResourceManager.GetString("TestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestName.
        /// </summary>
        internal static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests And Lab Tests.
        /// </summary>
        internal static string TestsAndLabTests {
            get {
                return ResourceManager.GetString("TestsAndLabTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Is Debt.
        /// </summary>
        internal static string ThisIsDebt {
            get {
                return ResourceManager.GetString("ThisIsDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Note Is Required.
        /// </summary>
        internal static string ThisNoteIsRequired {
            get {
                return ResourceManager.GetString("ThisNoteIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Payouts.
        /// </summary>
        internal static string TodayPayouts {
            get {
                return ResourceManager.GetString("TodayPayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Visits.
        /// </summary>
        internal static string TodayVisits {
            get {
                return ResourceManager.GetString("TodayVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total  Cost :.
        /// </summary>
        internal static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income.
        /// </summary>
        internal static string TotalIncome {
            get {
                return ResourceManager.GetString("TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Patients :.
        /// </summary>
        internal static string TotalPatients {
            get {
                return ResourceManager.GetString("TotalPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Remaining.
        /// </summary>
        internal static string TotalRemaining {
            get {
                return ResourceManager.GetString("TotalRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Name.
        /// </summary>
        internal static string UsageName {
            get {
                return ResourceManager.GetString("UsageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Notes.
        /// </summary>
        internal static string VisitNotes {
            get {
                return ResourceManager.GetString("VisitNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        internal static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone.
        /// </summary>
        internal static string WorkPhone {
            get {
                return ResourceManager.GetString("WorkPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
